#!/bin/sh
# TrimuiUpdate_MinUI.zip/updater

sync

DIR=$(dirname "$0")
SD=/mnt/SDCARD

if [ -d "$SD/System.pak" ]; then
	ACTION="update"
else
	ACTION="install"
fi

notify 0 "$ACTION MinUI"
sleep 1

notify 33 "$ACTION system"
rm -rf "$SD/System.pak" && sync
mv -f "$DIR/System.pak" "$SD"

rm -rf "$SD/Update.pak" && sync
mv -f "$DIR/Update.pak" "$SD"
sync

notify 66 "$ACTION boot"
rm -f "$DIR/updater" && sync
mv -f "$DIR/launch.sh" "$DIR/updater"

rm -f "$SD/TrimuiUpdate_MinUI.zip" && sync
mv -f "$DIR/TrimuiUpdate_MinUI.zip" "$SD"
sync

notify 100 "MinUI $ACTION done"
sleep 1

"$SD/System.pak/launch.sh"