#!/bin/sh
sync

DIR=$(dirname ${0})

if [ -f /usr/trimui/bin/StockUI ] ; then
	notify 100 already installed
else
	
	notify 0 renaming MainUI to StockUI
	mv /usr/trimui/bin/MainUI /usr/trimui/bin/StockUI
	
	sleep 1
	
	notify 33 installing faux MainUI
	cp -f $(DIR)/MainUI /usr/trimui/bin/MainUI
	
	sleep 1
	
	notify 66 installing libmmenu.so
	cp $(DIR)/libmmenu.so /usr/trimui/lib
	chmod 0755 /usr/trimui/lib/libmmenu.so
	
	sleep 1
	
	notify 100 installed MinUI
fi

sync
sleep 1
notify 100 quit